### ISSUE TITLE
Password change dialog missing i18n DE

### ISSUE THREAD

**Issue by rasos** [faircoin/electrumfair#12]
Password change is partially in English and says "bitcoin"

![bildschirmfoto_2018-02-11_21-56-25](https://user-images.githubusercontent.com/485723/36078430-6c61ee60-0f76-11e8-8ad9-c0de57a5db96.png)

recommendation: say "coins"

**Comment by thokon00** [comment]
Please install the latest version form https://download.faircoin.world/ and the issue should be gone.
Like this:
`sudo pip3 install --upgrade https://download.faircoin.world/electrum/ElectrumFair-3.0.5.tar.gz`

**Comment by rasos** [comment]
Fixed, when installed with pip3.
